# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: local
  hooks:
  - id: docker-compose-setup
    name: Docker Compose Setup
    language: system
    entry: docker compose -f docker-compose.test.yaml down
    pass_filenames: false
    always_run: true
  - id: docker-compose-run
    name: Docker Compose Run
    language: system
    entry: docker compose -f docker-compose.test.yaml run --remove-orphans --build --rm -T tests
    pass_filenames: false
    always_run: true
  - id: docker-compse-cleanup
    name: Docke Compose Cleanup
    language: system
    entry: docker compose -f docker-compose.test.yaml down
    pass_filenames: false
    always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--line-length=2000]
