# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: local
  hooks:
  - id: docker-compose-test
    name: Docker Compose Test
    language: system
    entry: scripts/docker-compose-test.sh run --rm --remove-orphans --build tests
    pass_filenames: false
    always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--line-length=2000]
