version: "3"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
    env_file:
      - .env
    depends_on:
      alembic:
        condition: service_completed_successfully
    command: python -m pytest .

  alembic:
    extends:
      file: docker-compose.common.yml
      service: alembic

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
