version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      alembic:
        condition: service_completed_successfully

  alembic:
    extends:
      file: docker-compose.common.yml
      service: alembic

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
