version: "3"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python -m pytest .

  postgres:
    extends:
      file: docker-compose.common.yaml
      service: postgres
