version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
