version: "3"

services:
  browser-sync:
    build:
      context: .
      dockerfile: Dockerfile.npm
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      web:
        condition: service_started
    attach: false
    command: npx browser-sync start --proxy "web:8000" --watch --files .

  web:
    build: .
    env_file:
      - .env
    depends_on:
      alembic:
        condition: service_completed_successfully
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    command: uvicorn app.app:app --host 0.0.0.0 --port $PORT --reload

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.npm
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./tailwind.config.js:/app/tailwind.config.js
    stdin_open: true
    attach: false
    command: npx tailwindcss -o static/dist/tailwind.css --watch

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.npm
    volumes:
      - ./static:/app/static
      - ./js:/app/js
      - ./webpack.config.js:/app/webpack.config.js
    attach: false
    command: npx webpack --mode development --watch

  alembic:
    extends:
      file: docker-compose.common.yml
      service: alembic

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
