version: "3"

services:
  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./tests:/app/tests
    env_file:
      - .env
    depends_on:
      postgres-test-db:
        condition: service_healthy
    command: python -m pytest .

  postgres-test-db:
    hostname: postgres
    extends:
      file: docker-compose.common.yaml
      service: postgres
