version: "3"

services:
  browser-sync:
    build:
      context: .
      dockerfile: docker/Dockerfile.npm
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      web:
        condition: service_started
    attach: false
    command: npx browser-sync start --proxy "web:8000" --watch --files .

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      alembic:
        condition: service_completed_successfully
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
    command: uvicorn app.app:app --host 0.0.0.0 --port $PORT --reload

  tailwind:
    build:
      context: .
      dockerfile: docker/Dockerfile.npm
    volumes:
      - ./frontend:/app/frontend
      - ./tailwind.config.js:/app/tailwind.config.js
    stdin_open: true
    attach: false
    command: npx tailwindcss -o frontend/static/dist/tailwind.css --watch

  webpack:
    build:
      context: .
      dockerfile: docker/Dockerfile.npm
    volumes:
      - ./frontend:/app/frontend
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json
    attach: false
    command: npx webpack --mode development --watch

  alembic:
    volumes:
      - ./app/database:/app/app/database
    extends:
      file: docker-compose.common.yaml
      service: alembic

  postgres:
    extends:
      file: docker-compose.common.yaml
      service: postgres
