version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      alembic:
        condition: service_completed_successfully

  alembic:
    extends:
      file: docker-compose.common.yaml
      service: alembic

  postgres:
    extends:
      file: docker-compose.common.yaml
      service: postgres
