FROM node:latest

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install

COPY tailwind.config.js tailwind.config.js
COPY webpack.config.js webpack.config.js

COPY frontend frontend
